### ISSUE TITLE
[FR] slim ps2 support and freedvdboot packaging

### ISSUE THREAD

**Issue by Wolverine-14** [ps2homebrew/OPL-Launcher#15]
### Checks

- [X] I have checked existing feature requests for duplicates and found none

### Describe the FR

I'd like to be able to burn a dvd that would allow my SCPH-90001 ps2 to boot directly into the opl elf on my memory card

### Describe the solution you'd like

if it was clear how to change the location that opl-launcher was looking at in order to launch [opl](https://github.com/ps2homebrew/Open-PS2-Loader) then it could point to the memory card or usb drive and execute the elf. this would allow the modification of the [freedvdboot](https://github.com/ps2homebrew/FreeDVDBoot) project to use opl-launcher in order to be able to make a burned disc that allows consoles that can't use freemcboot to not have to navigate menus like [opentuna](https://github.com/ps2homebrew/opentuna-installer) requires (helpful for those who's tvs don't recognize the default ps2 resolution)

**Comment by israpps** [comment]
this application purpose is to launch games from internal HDD without opening OPL UI (via other apps such as HDD-OSD or PSBBN)

IMO what you ask for escapes that purpose and its a foolish idea

wasting the lifespan of your laser just because you dont like the way OpenTuna works...

**Comment by Wolverine-14** [comment]
@israpps thanks for the reply. I clearly had misunderstood what the point of this application was and agree that it is out of the scope for this project. 

I still think that for those of us who's TV can't see the ps2's menu because the TV can't see the 480i or lower resolution could still benefit from what I suggested and as it shouldn't need to constantly be using the laser I don't see that wearing out quickly as an issue.

regardless I'll close this feature request as it is out of the scope of the project
